// Generated by `neat init --apply` (ADR-073). Next.js instrumentation hook.
import { readFileSync as __neatReadFileSync } from 'node:fs'
import { join as __neatJoin, dirname as __neatDirname } from 'node:path'
process.env.OTEL_SERVICE_NAME ||= 'edgecase'
;(function () {
  try {
    if (process.env.OTEL_EXPORTER_OTLP_TRACES_ENDPOINT || process.env.OTEL_EXPORTER_OTLP_ENDPOINT) return
    let __neatDir = process.cwd()
    for (let __i = 0; __i < 8; __i++) {
      try {
        const __rec = JSON.parse(__neatReadFileSync(__neatJoin(__neatDir, 'neat-out', 'daemon.json'), 'utf8'))
        if (__rec && __rec.ports && typeof __rec.ports.otlp === 'number') {
          process.env.OTEL_EXPORTER_OTLP_TRACES_ENDPOINT = 'http://localhost:' + __rec.ports.otlp + '/v1/traces'
          break
        }
      } catch (_e) {}
      const __parent = __neatDirname(__neatDir)
      if (__parent === __neatDir) break
      __neatDir = __parent
    }
  } catch (_e) {}
  process.env.OTEL_EXPORTER_OTLP_TRACES_ENDPOINT ||= 'http://localhost:4318/v1/traces'
})()
process.env.OTEL_EXPORTER_OTLP_PROTOCOL ||= 'http/json'
if (process.env.NEAT_OTEL_TOKEN) process.env.OTEL_EXPORTER_OTLP_HEADERS ||= 'Authorization=Bearer ' + process.env.NEAT_OTEL_TOKEN

import { NodeSDK } from '@opentelemetry/sdk-node'
import { getNodeAutoInstrumentations } from '@opentelemetry/auto-instrumentations-node'

const instrumentations = [getNodeAutoInstrumentations()]
new NodeSDK({ instrumentations }).start()
